##########################################################
## Node-RED Stack or Compose

version: "2"

services:

  nodered:
    image: dennislaurel/node-red-firebase:0.2
    ports:
       - 1880:1880
    volumes:
       - /usr/share/zoneinfo/America/La_Paz:/etc/localtime
       - /ruote/file:/data
    restart: unless-stopped
